CREATE TABLE `cpws_batch` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `doc_id` varchar(255) DEFAULT NULL,
  `source` text,
  `error_msg` text,
  `crawl_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `status` tinyint(4) DEFAULT NULL COMMENT '0/1 成功/失败',
  PRIMARY KEY (`id`),
  INDEX `ix_status` (`status`),
  INDEX `ix_doc_id` (`doc_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3177 DEFAULT CHARSET=utf8
PARTITION BY RANGE (id)
(PARTITION p0 VALUES LESS THAN (4000000) ENGINE = InnoDB,
 PARTITION p1 VALUES LESS THAN (8000000) ENGINE = InnoDB,
 PARTITION p2 VALUES LESS THAN (12000000) ENGINE = InnoDB,
 PARTITION p3 VALUES LESS THAN (16000000) ENGINE = InnoDB,
 PARTITION p4 VALUES LESS THAN (20000000) ENGINE = InnoDB,
 PARTITION p5 VALUES LESS THAN (24000000) ENGINE = InnoDB,
 PARTITION p6 VALUES LESS THAN (28000000) ENGINE = InnoDB,
 PARTITION p7 VALUES LESS THAN (32000000) ENGINE = InnoDB,
 PARTITION p8 VALUES LESS THAN (36000000) ENGINE = InnoDB,
 PARTITION p9 VALUES LESS THAN (40000000) ENGINE = InnoDB,
 PARTITION p10 VALUES LESS THAN (44000000) ENGINE = InnoDB,
 PARTITION p11 VALUES LESS THAN MAXVALUE ENGINE = InnoDB);


 CREATE TABLE `cpws_doc_id` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `doc_id` varchar(50) NOT NULL,
  `status` tinyint(4) DEFAULT '0' COMMENT '0/1 未成功抓取/已成功抓取',
  `last_update_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`,`doc_id`),
  INDEX `idx_status` (`status`),
  INDEX `idx_doc_id` (`doc_id`)
) ENGINE=InnoDB AUTO_INCREMENT=274004 DEFAULT CHARSET=utf8mb4;
